{
  "comments": [
    {
      "key": {
        "uuid": "127db0f6_6886b54b",
        "filename": "tests/test_data.py",
        "patchSetId": 3
      },
      "lineNbr": 81,
      "author": {
        "id": 123
      },
      "writtenOn": "2018-09-26T16:40:54Z",
      "side": 1,
      "message": "this is the line that is failing in the tests now, unexpectadly. Are we sure \u0027fakemodelid_100_proto\u0027 cooresponds to the new fixture \"test_proto_mid\"? (just a guess here. otherwise, there is something else wrong)",
      "revId": "a7667400e9759303a692a85ef3b3d1c84293244c",
      "serverId": "655300a2-7a56-4504-9153-881edd907bea",
      "unresolved": false
    }
  ]
}